### ISSUE TITLE
Version 1.0.0-1.19.4-fabric is incorrectly marked as compatible with 1.20.1 on modrinth

### ISSUE THREAD

**Issue by RashidFTW** [FinnSetchell/MoogsNetherStructures#1]
I was going through the list of structures with the /locate to check them out. Twice when teleporting to circle_blackstone, my game crashed.

Tested it twice in newly generated worlds (once in a sandbox, with no other mods), issue persisted.

Steps to reproduce:
1. Generate a new world
2. Go to the nether (was in creative/spectator)
3. Use /locate command to find circle_blackstone structure
4. Teleport to it, be near it, fly around
5. Crash

Relevant info:
moogs-nether-structures-1.0.0-1.19.4-fabric.jar
[crash-2024-02-24_09.12.22-server.txt](https://github.com/FinnSetchell/MoogsNetherStructures/files/14391808/crash-2024-02-24_09.12.22-server.txt)

**Comment by RashidFTW** [comment]
This seems to be happening with other structures in mns too :<

Edit: Testing with `moogs-nether-structures-1.0-1.20-fabric.jar`, this doesn't seem to be an issue. In such case `moogs-nether-structures-1.0.0-1.19.4-fabric.jar` should be marked incompatible with 1.20.1 on modrinth

**Comment by FinnSetchell** [comment]
Thanks, I will fix this asap

**Comment by FinnSetchell** [comment]
apologies, seems i accidently marked the file as compatible with the wrong versions. All fixed now
